/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Ball({ x=0, y=0, z=0, position, rotation,scale, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Cricket ball.glb");

  useFrame((state, delta) => {
    group.current.rotation.x += x;
    group.current.rotation.y += y;
    group.current.rotation.z += z;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[10, 0, 0]} scale={scale} position={position}>
        <mesh
          geometry={nodes.Torus.geometry}
          material={materials["Harvest Time"]}
          position={[2.43, -0.26, 51.61]}
          rotation={[1.66, 1.42, 2.1]}
          scale={0.71}
        />
        <mesh
          geometry={nodes.Torus_1.geometry}
          material={materials["Harvest Time 1"]}
          position={[-5.62, 0.61, 51.78]}
          rotation={[1.57, 1.42, 2.22]}
          scale={0.71}
        />
        <mesh
          geometry={nodes["Sphere_-_baked"].geometry}
          material={materials.Aura}
          position={[1, -0.44, 1.67]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Cricket ball.glb");
